# Posteriors

## Posterior for $\tau$ 

- $p(\tau | \mu_1, \dots, \mu_m, y, \alpha, \beta, k)$

\begin{equation}
p(\tau | \mu_1, \dots, \mu_m, y, \alpha, \beta) \propto
\tau^{\alpha - 1} exp\{ - \beta \tau \}  \times \\

(\tau/k)^{m/2} exp \{ -\frac{\tau}{2k} \sum_{j = 1}^{m}
(\mu_{j} - \mu)^2 \} \times \\

\tau^{n/2} exp \{ -\frac{\tau}{2} \sum_{j = 1}^{m}
\sum_{i = 1}^{n_j} (y_{ij} - \mu_j)^2 \} \\

\propto \tau^{n/2  + m/2 + \alpha - 1 }
exp \{ - \tau \Big( \frac{\sum_{j = 1}^{m}
\sum_{i = 1}^{n_j} (y_{ij} - \mu_j)^2}{2} + \beta  +
\frac{\sum_{j = 1}^{m}(\mu_{j} - \mu)^2}{2k} \Big) \}
\end{equation}

So  $\tau | \mu_1, \dots, \mu_m, y, \alpha, \beta, k \sim 
\text{Gamma}(n/2  + m/2 + \alpha, 
\Big( \frac{\sum_{j = 1}^{m}
\sum_{i = 1}^{n_j} (y_{ij} - \mu_j)^2}{2} + \beta  +
\frac{\sum_{j = 1}^{m}(\mu_{j} - \mu)^2}{2k} \Big))$


## Posterior for $\mu_j$


\begin{equation}
Q =    (\tau/k) \sum_{j=1}^{m} (\mu_j - \mu)^2 + 
\tau \sum_{j = 1}^{m} \sum_{i = 1}^{n_j} (y_{ij} - \mu_j)^2 \\

Q =    \tau [ \sum_{j = 1}^{m} n_j \mu_j^2 + \frac{\mu_j^2}{k} -  
(\sum_{j = 1}^{m} \frac{2 \mu \mu_j}{k} + 2 \bar y_j n_j \mu_j)] \\

Q \propto    \tau [ \sum_{j = 1}^{m} (n_j + \frac{1}{k}) \mu_j^2 -  
2 \mu_j (\frac{\mu}{k} +  \bar y_j n_j )] \\

Q \propto \tau [ \sum_{j = 1}^{m} (n_j + \frac{1}{k})(\mu_j -  
 \frac{\mu/k +  \bar y_j n_j}{n_j + 1/k})^2]\\

\end{equation}
So for each $\mu_j$


$$\mu_j | \mu, y, \tau, k \sim N(\tau[\frac{\mu/k +  \bar y_j n_j}{n_j + 1/k}], (n_j + \frac{1}{k})^{-1} \tau)$$

## Posterior for $\mu$ 

Similarly, for $\mu$ we have: 

\begin{equation}
Q =    \frac{\tau}{k} \sum_{j = 1}^{m} (\mu_j - \mu)^2 +  \tau_{\mu}\mu^2 \\

Q =    \frac{\tau}{k}  \sum_{j=1}^{m} (\mu_j^{2} - 2 \mu \mu_j + \mu^2) + 
\tau_{\mu} \mu^2 \\


Q \propto (\tau_{\mu} + \frac{\tau}{k}  m ) \mu^2 - 
\frac{2\tau}{k} \sum_{j=1}^{m} \mu \mu_j \\

Q \propto (\tau_{\mu} + \frac{\tau}{k}  m ) \mu^2 - 
\frac{2\tau}{k}  \mu \bar \mu m \\


Q \propto (\tau_{\mu} + \frac{\tau}{k}  m )(\mu - 
\frac{(\tau/k) \bar \mu m}{\tau_{\mu} + \frac{\tau}{k}  m})^2

\end{equation}

So for $\mu$ we have that the conditional distribution: 

$$\mu | \mu_1, \dots, \mu_{m}, \mu_{\mu}, \tau_{\mu}, k \sim N(
\frac{(\tau/k) \bar \mu m}{\tau_{\mu} + \frac{\tau}{k}  m},
(\tau_{\mu} + \frac{\tau}{k}  m )^{-1})$$
