---
title: "Bayesian hierarchical modelling by hand"
author: "Andrew Parnell & Emma Govan"
date: "7/23/2020"
output: 
  html_document:
    number_sections: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Define the following model. Suppose we have data:
$$y_{ij}, i = 1,\ldots,n_j, \; j = 1\ldots, m$$
where $y_{ij}$ is observation $i$ in group $j$. There are different numbers of observations $n_j$ in each group, so for example $n_1$ is the number of observations in group 1, etc. There are $m$ groups. The total number of observations is $n = \sum_{j=1}^m n_j$

Suppose have a likelihood:
$$y_{ij} \sim N(\mu_j, \tau^{-1})$$

so each group has an overall mean $\mu_j$, with an overall precision term $\tau$. 

We then have a hierarchical prior distribution:

$$\mu_j \sim N(\mu, \omega^{-1})$$

and hyper-parameter prior distributions:

$$\mu \sim N(\mu_\mu, \tau_\mu)$$
$$\tau \sim Ga(\alpha, \beta)$$
$$\omega \sim Ga(\alpha_\omega, \beta_\omega)$$

Where the values $\mu_\mu, \tau_\mu, \alpha, \beta, \alpha_\omega, \beta_\omega$ are all fixed.

Your task is to create an .Rmd document that contains:

- The model above coded up in JAGS/Stan
- The maths outlining the posterior distribution up to a constant of proportionality
- The maths for a Gibbs Sampling implementation of the model
- The code for a Gibbs Sampling implementation of the model in R
- The code for a Metropolis-Hastings implementation of the model in R
- Suitable plots which show that e.g. the posterior distribution of $\mu$ matches for all the implementations

You should implement the code on the Wolves data set from the MixSIAR package (first isotope only) using region as the group. 



